FROM openjdk:8
ADD ProfileMicroserviceConsumer-0.0.1-SNAPSHOT.jar ProfileMicroserviceConsumer-0.0.1-SNAPSHOT.jar
EXPOSE 9096
ENTRYPOINT ["java","-jar","ProfileMicroserviceConsumer-0.0.1-SNAPSHOT.jar"]