FROM openjdk:8
ADD MicroserviceDiscoveryServer-0.0.1-SNAPSHOT.jar MicroserviceDiscoveryServer-0.0.1-SNAPSHOT.jar
EXPOSE 9095
ENTRYPOINT ["java","-jar","MicroserviceDiscoveryServer-0.0.1-SNAPSHOT.jar"]