FROM openjdk:8
ADD ProfileMicroserviceProducer-0.0.1-SNAPSHOT.jar ProfileMicroserviceProducer-0.0.1-SNAPSHOT.jar
EXPOSE 9097
ENTRYPOINT ["java","-jar","ProfileMicroserviceProducer-0.0.1-SNAPSHOT.jar"]